services:
  backend:
    container_name: ws-back
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3011:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    # depends_on:
    #   - db
    # environment:
    #   NODE_ENV: development
    # command: npm run dev

  frontend:
    restart: always
    container_name: ws-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    # env_file:
    #   - ./frontend/.env
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      # - /app/node_modules

  db:
    image: postgres:13
    container_name: ws-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./backend/.env
        # required: "true"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: